[package]
name = "ente"
version = "0.2.0"
authors = ["Luis de Bethencourt <luisbg@debethencourt.com>"]

[dependencies]
rustbox = "*"
error-chain = "*"
slog = "*"
slog-stream = "*"
slog-scope = "*"
time = "*"
docopt = "*"
rustc-serialize = "*"
